openapi: 3.0.3
info:
  title: Muric Transmission Status
  version: 1.0.0
  description: This service integrates sfc exposed service to consult the status of a report submission with its transmission_id
  x-implemented-by: bamartrod@gmail.com
paths:
  /muric/transmission-status/get:
    post:
      operationId: GetTransmissionStatus
      tags:
        - muric
      summary: Query for transmission status
      description: This service obtains the report submission with its transmission_id
      parameters:
        - $ref: '#/components/parameters/BaseHeader'
#      security:
#        - oAuth2ClientCredentials:
#          - co:muric:transmission:status:read
      requestBody:
        description: Data required to query transmission_id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HashMap'
            examples:
              Request: 
                $ref: '#/components/examples/Request'
      responses:
        "200":
          description: Request Successfully Processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
              examples:
                SuccessResponseExample:
                  $ref: '#/components/examples/SuccessResponseExample'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
              examples:
                BadRequestErrorExample:
                  $ref: '#/components/examples/BadRequestErrorExample'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
              examples:
                UnauthorizedRequestErrorExample:
                  $ref: '#/components/examples/UnauthorizedRequestErrorExample'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
              examples:
                InternalServerErrorExample:
                  $ref: '#/components/examples/InternalServerErrorExample'
components:
  schemas:
    HashMap:
      type: object
      additionalProperties:
        type: string
    GeneralResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/HashMap'
        notification:
          type: array
          items:
            $ref: '#/components/schemas/HashMap'
  parameters:
    BaseHeader:
      name: x-b3-traceid
      in: header
      required: true
      schema:
        type: string
      description: "Defining header"
  examples:
    Request:
      value:
        transmission_id: "1234567890" 
    SuccessResponseExample:
      value: 
        data:
          status: "enum-based-string"
          timestamp: "date-formatted-string"
          entity_code: "number-formatted-string"
        notification: []
    BadRequestErrorExample:
      value: 
        data: {}
        notification: 
          - category: "BAD REQUEST"
            code: "400"
            message: "Error title"
            description: "Error detail"
    UnauthorizedRequestErrorExample:
      value: 
        data: {}
        notification: 
          - category: "Unauthorized"
            code: "401"
            message: "Error title"
            description: "Error detail"
    InternalServerErrorExample:
      value: 
        data: {}
        notification: 
          - category: "Internal Server Error"
            code: "500"
            message: "Error title"
            description: "Error detail"
# regex-utilities: 
  # iniciar con ^[ para rechazar lo que haga match
  # finalizar con ]+$ para evaluar que llegue hasta el final
  # usar () para agrupar relacionando secuencia entre regex
  # mayuscula: a-z, minuscula: A-Z
  # length max: {20}, max & min: {10,20}
  # numeros 0-9 o \d
  # phone number: ^\+\d{1,5})(\d{10}$
  # email: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  # timestamp: ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
